version: '3.4'
services:

  # "devbox" to enable the developer to have a fully loaded development environment
  # to test new code using say IPython and other common tools.
  devbox: &devbox
    build:
      dockerfile: ./docker/devbox.dockerfile
      context: .
    image: "ocamlmycaml/stateman-devbox"
    command: python
    volumes:
    - ./:/app

  test:
    <<: *devbox
    entrypoint: make test && make lint
